// ***********************************************************************
// Assembly         : ACBr.Net.Sat
// Author           : RFTD
// Created          : 03-31-2016
//
// Last Modified By : RFTD
// Last Modified On : 03-31-2016
// ***********************************************************************
// <copyright file="SatResposta.cs" company="ACBr.Net">
//		        		   The MIT License (MIT)
//	     		    Copyright (c) 2016 Grupo ACBr.Net
//
//	 Permission is hereby granted, free of charge, to any person obtaining
// a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//	 The above copyright notice and this permission notice shall be
// included in all copies or substantial portions of the Software.
//	 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
// </copyright>
// <summary>
// Classe feita para tratar o retorno do SAT
// </summary>
// ***********************************************************************
using System.Collections.Generic;

namespace ACBr.Net.Sat
{
	public static class CodigosSat
	{
		// Retorna a mensagem de erro do código no parametro CodigoRetorno de acordo com a NOTA TECNICA 2013/001
		public static Dictionary<int, string> CodigoRetorno = new Dictionary<int, string>
		{
			{04000, "Ativado corretamente SAT Ativado com Sucesso."},
			{04001, "Erro na criação do certificado processo de ativação foi interrompido."},
			{04002, "SEFAZ não reconhece este SAT (CNPJ inválido) Verificar junto a SEFAZ o CNPJ cadastrado."},
			{04003, "SAT já ativado SAT disponível para uso."},
			{04004, "SAT com uso cessado SAT bloqueado por cessação de uso."},
			{04005, "Erro de comunicação com a SEFAZ Tentar novamente."},
			{04006, "CSR ICP-BRASIL criado com sucesso Processo de criação do CSR para certificação ICP-BRASIL com sucesso"},
			{04007, "Erro na criação do CSR ICP-BRASIL Processo de criação do CSR para certificação ICP-BRASIL com erro"},
			{04098, "SAT em processamento. Tente novamente."},
			{04099, "Erro desconhecido na ativação Informar ao administrador."},
			{05000, "Certificado transmitido com Sucesso "},
			{05001, "Código de ativação inválido."},
			{05002, "Erro de comunicação com a SEFAZ. Tentar novamente."},
			{05003, "Certificado Inválido "},
			{05098, "SAT em processamento."},
			{05099, "Erro desconhecido Informar o administrador."},
			{06000, "Emitido com sucesso + conteúdo notas. Retorno CF-e-SAT ao AC para contingência."},
			{06001, "Código de ativação inválido."},
			{06002, "SAT ainda não ativado. Efetuar ativação."},
			{06003, "SAT não vinculado ao AC Efetuar vinculação"},
			{06004, "Vinculação do AC não confere Efetuar vinculação"},
			{06005, "Tamanho do CF-e-SAT superior a 1.500KB"},
			{06006, "SAT bloqueado pelo contribuinte"},
			{06007, "SAT bloqueado pela SEFAZ"},
			{06008, "SAT bloqueado por falta de comunicação"},
			{06009, "SAT bloqueado, código de ativação incorreto"},
			{06010, "Erro de validação do conteúdo."},
			{06098, "SAT em processamento."},
			{06099, "Erro desconhecido na emissão. Informar o administrador."},
			{07000, "Cupom cancelado com sucesso + conteúdo CF-eSAT cancelado."},
			{07001, "Código ativação inválido Verificar o código e tentar mais uma vez."},
			{07002, "Cupom inválido Informar o administrador."},
			{07003, "SAT bloqueado pelo contribuinte"},
			{07004, "SAT bloqueado pela SEFAZ"},
			{07005, "SAT bloqueado por falta de comunicação"},
			{07006, "SAT bloqueado, código de ativação incorreto"},
			{07007, "Erro de validação do conteúdo"},
			{07098, "SAT em processamento."},
			{07099, "Erro desconhecido no cancelamento."},
			{08000, "SAT em operação. Verifica se o SAT está ativo."},
			{08098, "SAT em processamento."},
			{08099, "Erro desconhecido. Informar o administrador."},
			{09000, "Emitido com sucesso Gera e envia um cupom de teste para SEFAZ, para verificar a comunicação."},
			{09001, "código ativação inválido Verificar o código e tentar mais uma vez."},
			{09002, "SAT ainda não ativado. Efetuar ativação "},
			{09098, "SAT em processamento."},
			{09099, "Erro desconhecido Informar o "},
			{10000, "Resposta com Sucesso. Informações de status do SAT."},
			{10001, "Código de ativação inválido"},
			{10098, "SAT em processamento."},
			{10099, "Erro desconhecido Informar o administrador."},
			{11000, "Emitido com sucesso Retorna o conteúdo do CF-ao AC."},
			{11001, "código ativação inválido Verificar o código e tentar mais uma vez."},
			{11002, "SAT ainda não ativado. Efetuar ativação."},
			{11003, "Sessão não existe. AC deve executar a sessão novamente."},
			{11098, "SAT em processamento."},
			{11099, "Erro desconhecido. Informar o administrador."},
			{12000, "Rede Configurada com Sucesso"},
			{12001, "código ativação inválido Verificar o código e tentar mais uma vez."},
			{12002, "Dados fora do padrão a ser informado Corrigir dados"},
			{12098, "SAT em processamento."},
			{12099, "Erro desconhecido Informar o administrador."},
			{13000, "Assinatura do AC"},
			{13001, "código ativação inválido Verificar o código e tentar mais uma vez."},
			{13002, "Erro de comunicação com a SEFAZ"},
			{13003, "Assinatura fora do padrão informado Corrigir dados"},
			{13004, "CNPJ da Software House + CNPJ do emitente assinado no campo “signAC” difere do informado no campo “CNPJvalue” Corrigir dados"},
			{13098, "SAT em processamento."},
			{13099, "Erro desconhecido Informar o administrador."},
			{14000, "Software Atualizado com Sucesso "},
			{14001, "Código de ativação inválido."},
			{14002, "Atualização em Andamento"},
			{14003, "Erro na atualização Não foi possível Atualizar o SAT."},
			{14004, "Arquivo de atualização inválido"},
			{14098, "SAT em processamento."},
			{14099, "Erro desconhecido Informar o administrador."},
			{15000, "Transferência completa Arquivos de Logs extraídos"},
			{15001, "Código de ativação inválido."},
			{15002, "Transferência em andamento"},
			{15098, "SAT em processamento."},
			{15099, "Erro desconhecido Informar o administrador."},
			{16000, "Equipamento SAT bloqueado com sucesso."},
			{16001, "Código de ativação inválido."},
			{16002, "Equipamento SAT já está bloqueado."},
			{16003, "Erro de comunicação com a SEFAZ"},
			{16004, "Não existe parametrização de bloqueio disponível."},
			{16098, "SAT em processamento."},
			{16099, "Erro desconhecido Informar o administrador."},
			{17000, "Equipamento SAT desbloqueado com sucesso."},
			{17001, "Código de ativação inválido."},
			{17002, "SAT bloqueado pelo contribuinte. Verifique configurações na SEFAZ"},
			{17003, "SAT bloqueado pela SEFAZ"},
			{17004, "Erro de comunicação com a SEFAZ"},
			{17098, "SAT em processamento."},
			{17099, "Erro desconhecido Informar o administrador."},
			{18000, "Código de ativação alterado com sucesso."},
			{18001, "Código de ativação inválido."},
			{18002, "Código de ativação de emergência Incorreto."},
			{18098, "SAT em processamento."},
			{18099, "Erro desconhecido Informar o administrador."}
		};

		// Retorna a mensagem de rejeição do código no parametro pCodigo de acordo com a NOTA TECNICA 2013/001
		public static Dictionary<int, string> MotivocStat = new Dictionary<int, string>()
		{
			{100, "CF-e-SAT processado com sucesso"},
			{101, "CF-e-SAT de cancelamento processado com sucesso"},
			{102, "CF-e-SAT processado – verificar inconsistências"},
			{103, "CF-e-SAT de cancelamento processado – verificar inconsistências"},
			{104, "Não Existe Atualização do Software"},
			{105, "Lote recebido com sucesso"},
			{106, "Lote Processado"},
			{107, "Lote em Processamento"},
			{108, "Lote não localizado"},
			{109, "Serviço em Operação"},
			{110, "Status SAT recebido com sucesso"},
			{112, "Assinatura do AC Registrada"},
			{113, "Consulta cadastro com uma ocorrência"},
			{114, "Consulta cadastro com mais de uma ocorrência"},
			{115, "Solicitação de dados efetuada com sucesso"},
			{116, "Atualização do SB pendente"},
			{117, "Solicitação de Arquivo de Parametrização efetuada com sucesso"},
			{118, "Logs extraídos com sucesso"},
			{119, "Comandos da SEFAZ pendentes"},
			{120, "Não existem comandos da SEFAZ pendentes"},
			{121, "Certificado Digital criado com sucesso"},
			{122, "CRT recebido com sucesso"},
			{123, "Adiar transmissão do lote"},
			{124, "Adiar transmissão do CF-e"},
			{125, "CF-e de teste de produção emitido com sucesso"},
			{126, "CF-e de teste de ativação emitido com sucesso"},
			{127, "Erro na emissão de CF-e de teste de produção"},
			{128, "Erro na emissão de CF-e de teste de ativação"},
			{129, "Solicitações de emissão de certificados excedidas. (Somente ocorrerá no ambiente de testes)"},
			{200, "Rejeição: Status do equipamento SAT difere do esperado"},
			{201, "Rejeição: Falha na Verificação da Assinatura do Número de segurança"},
			{202, "Rejeição: Falha no reconhecimento da autoria ou integridade do arquivo digital"},
			{203, "Rejeição: Emissor não Autorizado para emissão da CF-e-SAT"},
			{204, "Rejeição: Duplicidade de CF-e-SAT"},
			{205, "Rejeição: Equipamento SAT encontra-se Ativo"},
			{206, "Rejeição: Hora de Emissão do CF-e-SAT posterior à hora de recebimento."},
			{207, "Rejeição: CNPJ do emitente inválido"},
			{208, "Rejeição: Equipamento SAT encontra-se Desativado"},
			{209, "Rejeição: IE do emitente inválida"},
			{210, "Rejeição: Intervalo de tempo entre o CF-e-SAT emitido e a emissão do respectivo CF-e-SAT de cancelamento é maior que 30 (trinta) minutos."},
			{211, "Rejeição: CNPJ não corresponde ao informado no processo de transferência."},
			{212, "Rejeição: Data de Emissão do CF-e-SAT posterior à data de recebimento."},
			{213, "Rejeição: CNPJ-Base do Emitente difere do CNPJ-Base do Certificado Digital"},
			{214, "Rejeição: Tamanho da mensagem excedeu o limite estabelecido"},
			{215, "Rejeição: Falha no schema XML"},
			{216, "Rejeição: Chave de Acesso difere da cadastrada"},
			{217, "Rejeição: CF-e-SAT não consta na base de dados da SEFAZ"},
			{218, "Rejeição: CF-e-SAT já esta cancelado na base de dados da SEFAZ"},
			{219, "Rejeição: CNPJ não corresponde ao informado no processo de declaração de posse."},
			{220, "Rejeição: Valor do rateio do desconto sobre subtotal do item (N) inválido."},
			{221, "Rejeição: Aplicativo Comercial não vinculado ao SAT"},
			{222, "Rejeição: Assinatura do Aplicativo Comercial inválida"},
			{223, "Rejeição: CNPJ do transmissor do lote difere do CNPJ do transmissor da consulta"},
			{224, "Rejeição: CNPJ da Software House inválido"},
			{225, "Rejeição: Falha no Schema XML do lote de CFe"},
			{226, "Rejeição: Código da UF do Emitente diverge da UF receptora"},
			{227, "Rejeição: Erro na Chave de Acesso - Campo Id – falta a literal CFe"},
			{228, "Rejeição: Valor do rateio do acréscimo sobre subtotal do item (N) inválido."},
			{229, "Rejeição: IE do emitente não informada"},
			{230, "Rejeição: IE do emitente não autorizada para uso do SAT"},
			{231, "Rejeição: IE do emitente não vinculada ao CNPJ"},
			{232, "Rejeição: CNPJ do destinatário do CF-e-SAT de cancelamento diferente daquele do CF-e-SAT a ser cancelado."},
			{233, "Rejeição: CPF do destinatário do CF-e-SAT de cancelamento diferente daquele do CF-e-SAT a ser cancelado."},
			{234, "Alerta: Razão Social/Nome do destinatário em branco"},
			{235, "Rejeição: CNPJ do destinatario Invalido"},
			{236, "Rejeição: Chave de Acesso com dígito verificador inválido"},
			{237, "Rejeição: CPF do destinatario Invalido"},
			{238, "Rejeição: CNPJ do emitente do CF-e-SAT de cancelamento diferente do CNPJ do CF-e-SAT a ser cancelado."},
			{239, "Rejeição: Versão do arquivo XML não suportada"},
			{240, "Rejeição: Valor total do CF-e-SAT de cancelamento diferente do Valor total do CF-e-SAT a ser cancelado."},
			{241, "Rejeição: diferença de transmissão e recebimento da mensagem superior a 5 minutos."},
			{242, "Alerta: CFe dentro do lote estão fora de ordem."},
			{243, "Rejeição: XML Mal Formado"},
			{244, "Rejeição: CNPJ do Certificado Digital difere do CNPJ da Matriz e do CNPJ do Emitente"},
			{245, "Rejeição: CNPJ Emitente não autorizado para uso do SAT"},
			{246, "Rejeição: Campo cUF inexistente no elemento cfeCabecMsg do SOAP Header"},
			{247, "Rejeição: Sigla da UF do Emitente diverge da UF receptora"},
			{248, "Rejeição: UF do Recibo diverge da UF autorizadora"},
			{249, "Rejeição: UF da Chave de Acesso diverge da UF receptora"},
			{250, "Rejeição: UF informada pelo SAT, não é atendida pelo Web Service"},
			{251, "Rejeição: Certificado enviado não confere com o escolhido na declaração de posse"},
			{252, "Rejeição: Ambiente informado diverge do Ambiente de recebimento"},
			{253, "Rejeição: Digito Verificador da chave de acesso composta inválida"},
			{254, "Rejeição: Elemento cfeCabecMsg inexistente no SOAP Header"},
			{255, "Rejeição: CSR enviado inválido"},
			{256, "Rejeição: CRT enviado inválido"},
			{257, "Rejeição: Número do série do equipamento inválido"},
			{258, "Rejeição: Data e/ou hora do envio inválida"},
			{259, "Rejeição: Versão do leiaute inválida"},
			{260, "Rejeição: UF inexistente"},
			{261, "Rejeição: Assinatura digital não encontrada"},
			{262, "Rejeição: CNPJ da software house não está ativo"},
			{263, "Rejeição: CNPJ do contribuinte não está ativo"},
			{264, "Rejeição: Base da receita federal está indisponível"},
			{265, "Rejeição: Número de série inexistente no cadastro do equipamento"},
			{266, "Falha na comunicação com a AC-SAT"},
			{267, "Erro desconhecido na geração do certificado pela AC-SAT"},
			{268, "Rejeição: Certificado está fora da data de validade."},
			{269, "Rejeição: Tipo de atividade inválida"},
			{270, "Rejeição: Chave de acesso do CFe a ser cancelado inválido."},
			{271, "Rejeição: Ambiente informado no CF-e difere do Ambiente de recebimento cadastrado."},
			{272, "Rejeição: Valor do troco negativo."},
			{273, "Rejeição: Serviço Solicitado Inválido"},
			{274, "Rejeição: Equipamento não possui declaração de posse"},
			{275, "Rejeição: Status do equipamento diferente de Fabricado"},
			{276, "Rejeição: Diferença de dias entre a data de emissão e de recepção maior que o prazo legal"},
			{277, "Rejeição: CNPJ do emitente não está ativo junto à Sefaz na data de emissão"},
			{278, "Rejeição: IE do emitente não está ativa junto à Sefaz na data de emissão"},
			{280, "Rejeição: Certificado Transmissor Inválido"},
			{281, "Rejeição: Certificado Transmissor Data Validade"},
			{282, "Rejeição: Certificado Transmissor sem CNPJ"},
			{283, "Rejeição: Certificado Transmissor - erro Cadeia de Certificação"},
			{284, "Rejeição: Certificado Transmissor revogado"},
			{285, "Rejeição: Certificado Transmissor difere ICP-Brasil"},
			{286, "Rejeição: Certificado Transmissor erro no acesso a LCR"},
			{287, "Rejeição: Código Município do FG - ISSQN: dígito inválido. Exceto os códigos descritos no Anexo 2 que apresentam dígito inválido."},
			{288, "Rejeição: Data de emissão do CF-e-SAT a ser cancelado inválida"},
			{289, "Rejeição: Código da UF informada diverge da UF solicitada"},
			{290, "Rejeição: Certificado Assinatura inválido"},
			{291, "Rejeição: Certificado Assinatura Data Validade"},
			{292, "Rejeição: Certificado Assinatura sem CNPJ"},
			{293, "Rejeição: Certificado Assinatura - erro Cadeia de Certificação"},
			{294, "Rejeição: Certificado Assinatura revogado"},
			{295, "Rejeição: Certificado Raiz difere dos Válidos"},
			{296, "Rejeição: Certificado Assinatura erro no acesso a LCR"},
			{297, "Rejeição: Assinatura difere do calculado"},
			{298, "Rejeição: Assinatura difere do padrão do Projeto"},
			{299, "Rejeição: Hora de emissão do CF-e-SAT a ser cancelado inválida"},
			{402, "Rejeição: XML da área de dados com codificação diferente de UTF-8"},
			{403, "Rejeição: Versão do leiaute do CF-e-SAT não é válida"},
			{404, "Rejeição: Uso de prefixo de namespace não permitido"},
			{405, "Alerta: Versão do leiaute do CF-e-SAT não é a mais atual"},
			{406, "Rejeição: Versão do Software Básico do SAT não é valida."},
			{407, "Rejeição: Indicador de CF-e-SAT cancelamento inválido (diferente de „C? e „?)"},
			{408, "Rejeição: Valor total do CF-e-SAT maior que o somatório dos valores de Meio de Pagamento empregados em seu pagamento."},
			{409, "Rejeição: Valor total do CF-e-SAT supera o máximo permitido no arquivo de Parametrização de Uso"},
			{410, "Rejeição: UF informada no campo cUF não é atendida pelo Web Service"},
			{411, "Rejeição: Campo versaoDados inexistente no elemento cfeCabecMsg do SOAP Header"},
			{412, "Rejeição: CFe de cancelamento não corresponde ao CFe anteriormente gerado"},
			{420, "Rejeição: Cancelamento para CF-e-SAT já cancelado"},
			{450, "Rejeição: Modelo da CF-e-SAT diferente de 59"},
			{452, "Rejeição: número de série do SAT inválido ou não autorizado."},
			{453, "Rejeição: Ambiente de processamento inválido (diferente de 1 e 2)"},
			{454, "Rejeição: CNPJ da Software House inválido"},
			{455, "Rejeição: Assinatura do Aplicativo Comercial não é válida."},
			{456, "Rejeição: Código de Regime tributário invalido"},
			{457, "Rejeição: Código de Natureza da Operação para ISSQN inválido"},
			{458, "Rejeição: Razão Social/Nome do destinatário em branco"},
			{459, "Rejeição: Código do produto ou serviço em branco"},
			{460, "Rejeição: GTIN do item (N) inválido"},
			{461, "Rejeição: Descrição do produto ou serviço em branco"},
			{462, "Rejeição: CFOP não é de operação de saída prevista para CF-e-SAT"},
			{463, "Rejeição: Unidade comercial do produto ou serviço em branco"},
			{464, "Rejeição: Quantidade Comercial do item (N) inválido"},
			{465, "Rejeição: Valor unitário do item (N) inválido"},
			{466, "Rejeição: Valor bruto do item (N) difere de quantidade * Valor Unitário, considerando regra de arred/trunc."},
			{467, "Rejeição: Regra de calculo do item (N) inválida"},
			{468, "Rejeição: Valor do desconto do item (N) inválido"},
			{469, "Rejeição: Valor de outras despesas acessórias do item (N) inválido."},
			{470, "Rejeição: Valor líquido do Item do CF-e difere de Valor Bruto de Produtos e Serviços - desconto + Outras Despesas Acessórias – rateio do desconto sobre subtotal + rateio do acréscimo sobre subtotal "},
			{471, "Rejeição: origem da mercadoria do item (N) inválido (difere de 0, 1, 2, 3, 4, 5, 6 e 7)"},
			{472, "Rejeição: CST do Item (N) inválido (diferente de 00, 20, 90)"},
			{473, "Rejeição: Alíquota efetiva do ICMS do item (N) inválido."},
			{474, "Rejeição: Valor líquido do ICMS do Item (N) difere de Valor do Item * Aliquota Efetiva"},
			{475, "Rejeição: CST do Item (N) inválido (diferente de 40 e 41 e 50 e 60)"},
			{476, "Rejeição: Código de situação da operação - Simples Nacional - do Item (N) inválido (diferente de 102, 300 e 500)"},
			{477, "Rejeição: Código de situação da operação - Simples Nacional - do Item (N) inválido (diferente de 900)"},
			{478, "Rejeição: Código de Situação Tributária do PIS Inválido (diferente de 01 e 02)"},
			{479, "Rejeição: Base de cálculo do PIS do item (N) inválido."},
			{480, "Rejeição: Alíquota do PIS do item (N) inválido."},
			{481, "Rejeição: Valor do PIS do Item (N) difere de Base de Calculo * Aliquota do PIS"},
			{482, "Rejeição: Código de Situação Tributária do PIS Inválido (diferente de 03)"},
			{483, "Rejeição: Qtde Vendida do item (N) inválido."},
			{484, "Rejeição: Alíquota do PIS em R$ do item (N) inválido."},
			{485, "Rejeição: Valor do PIS do Item (N) difere de Qtde Vendida* Aliquota do PIS em R$"},
			{486, "Rejeição: Código de Situação Tributária do PIS Inválido (diferente de 04, 06, 07, 08 e 09)"},
			{487, "Rejeição: Código de Situação Tributária do PIS inválido (diferente de 49)"},
			{488, "Rejeição: Código de Situação Tributária do PIS Inválido (diferente de 99)"},
			{489, "Rejeição: Valor do PIS do Item (N) difere de Qtde Vendida* Aliquota do PIS em R$ e difere de Base de Calculo * Aliquota do PIS"},
			{490, "Rejeição: Código de Situação Tributária da COFINS Inválido (diferente de 01 e 02)"},
			{491, "Rejeição: Base de cálculo do COFINS do item (N) inválido."},
			{492, "Rejeição: Alíquota da COFINS do item (N) inválido."},
			{493, "Rejeição: Valor da COFINS do Item (N) difere de Base de Calculo * Aliquota da COFINS"},
			{494, "Rejeição: Código de Situação Tributária da COFINS Inválido (diferente de 03)"},
			{495, "Rejeição: Valor do COFINS do Item (N) difere de Qtde Vendida* Aliquota do COFINS em R$ e difere de Base de Calculo * Aliquota do COFINS"},
			{496, "Rejeição: Alíquota da COFINS em R$ do item (N) inválido."},
			{497, "Rejeição: Valor da COFINS do Item (N) difere de Qtde Vendida* Aliquota da COFINS em R$"},
			{498, "Rejeição: Código de Situação Tributária da COFINS Inválido (diferente de 04, 06, 07, 08 e 09)"},
			{499, "Rejeição: Código de Situação Tributária da COFINS Inválido (diferente de 49)"},
			{500, "Rejeição: Código de Situação Tributária da COFINS Inválido (diferente de 99)"},
			{501, "Rejeição: Operação com tributação de ISSQN sem informar a Inscrição Municipal"},
			{502, "Rejeição: Erro na Chave de Acesso - Campo Id não corresponde à concatenação dos campos correspondentes"},
			{503, "Rejeição: Valor das deduções para o ISSQN do item (N) inválido."},
			{504, "Rejeição: Valor da Base de Calculo do ISSQN do Item (N) difere de Valor do Item - Valor das deduções"},
			{505, "Rejeição: Alíquota efetiva do ISSQN do item (N) não é maior ou igual a 2,00 (2%) e menor ou igual a 5,00 (5%)."},
			{506, "Valor do ISSQN do Item (N) difere de Valor da Base de Calculo do ISSQN * Alíquota Efetiva do ISSQN"},
			{507, "Rejeição: Indicador de rateio para ISSQN inválido"},
			{508, "Rejeição: Item da lista de Serviços do ISSQN do item (N) inválido."},
			{509, "Rejeição: Código municipal de Tributação do ISSQN do Item (N) em branco."},
			{510, "Rejeição: Código de Natureza da Operação para ISSQN inválido"},
			{511, "Rejeição: Indicador de Incentivo Fiscal do ISSQN do item (N) inválido (diferente de 1 e 2)"},
			{512, "Rejeição: Total do PIS difere do somatório do PIS dos itens"},
			{513, "Rejeição: Total do COFINS difere do somatório do COFINS dos itens"},
			{514, "Rejeição: Total do PIS-ST difere do somatório do PIS-ST dos itens"},
			{515, "Rejeição: Total do COFINS-STdifere do somatório do COFINS-ST dos itens"},
			{516, "Rejeição: Total de Outras Despesas Acessórias difere do somatório de Outras Despesas Acessórias (acréscimo) dos itens"},
			{517, "Rejeição: Total dos Itens difere do somatório do valor líquido dos itens"},
			{518, "Rejeição: Informado grupo de totais do ISSQN sem informar grupo de valores de ISSQN"},
			{519, "Rejeição: Total da BC do ISSQN difere do somatório da BC do ISSQN dos itens"},
			{520, "Rejeição: Total do ISSQN difere do somatório do ISSQN dos itens"},
			{521, "Rejeição: Total do PIS sobre serviços difere do somatório do PIS dos itens de serviços"},
			{522, "Rejeição: Total do COFINS sobre serviços difere do somatório do COFINS dos itens de serviços"},
			{523, "Rejeição: Total do PIS-ST sobre serviços difere do somatório do PIS-ST dos itens de serviços"},
			{524, "Rejeição: Total do COFINS-ST sobre serviços difere do somatório do COFINS-ST dos itens de serviços"},
			{525, "Rejeição: Valor de Desconto sobre total inválido."},
			{526, "Rejeição: Valor de Acréscimo sobre total inválido."},
			{527, "Rejeição: Código do Meio de Pagamento inválido"},
			{528, "Rejeição: Valor do Meio de Pagamento inválido."},
			{529, "Rejeição: Valor de desconto sobre subtotal difere do somatório dos seus rateios nos itens."},
			{530, "Rejeição: Operação com tributação de ISSQN sem informar a Inscrição Municipal"},
			{531, "Rejeição: Valor de acréscimo sobre subtotal difere do somatório dos seus rateios nos itens."},
			{532, "Rejeição: Total do ICMS difere do somatório dos itens"},
			{533, "Rejeição: Valor aproximado dos tributos do CF-e-SAT – Lei 12741/12 inválido"},
			{534, "Rejeição: Valor aproximado dos tributos do Produto ou serviço – Lei 12741/12 inválido."},
			{535, "Rejeição: código da credenciadora de cartão de débito ou crédito inválido"},
			{537, "Rejeição: Total do Desconto difere do somatório dos itens"},
			{539, "Rejeição: Duplicidade de CF-e-SAT, com diferença na Chave de Acesso [99999999999999999999999999999999999999999]"},
			{540, "Rejeição: CNPJ da Software House + CNPJ do emitente assinado no campo “signAC” difere do informado no campo “CNPJvalue” "},
			{555, "Rejeição: Tipo autorizador do protocolo diverge do Órgão Autorizador"},
			{564, "Rejeição: Total dos Produtos ou Serviços difere do somatório do valor dos Produtos ou Serviços dos itens"},
			{600, "Serviço Temporariamente Indisponível"},
			{601, "CF-e-SAT inidôneo por recepção fora do prazo"},
			{602, "Rejeição: Status do equipamento não permite ativação"},
			{603, "Arquivo inválido"},
			{604, "Erro desconhecido na verificação de comandos"},
			{605, "Tamanho do arquivo inválido"},
			{999, "Rejeição: Erro não catalogado"}
		};

		public static Dictionary<int, string> MotivoInvalidoVenda = new Dictionary<int, string>()
		{
			{1002, "Código da UF não confere com a Tabela do IBGE"}, // | Válido até 31/12/2015
			{1003, "Código da UF diferente da UF registrada no SAT"}, // | Válido até 31/12/2015
			{1004, "Versão do leiaute do arquivo de entrada do SAT não é válida"},
			{1005, "Alerta Versão do leiaute do arquivo de entrada do SAT não é a mais atual"},
			{1226, "Código da UF do Emitente diverge da UF receptora"},
			{1450, "Código de modelo de documento fiscal diferente de 59"},
			{1258, "Data/hora inválida. Problemas com o relógio interno do SAT-CF-e"},
			{1224, "CNPJ da Software House inválido"},
			{1222, "Assinatura do Aplicativo Comercial não é válida"}, // | Válido até 31/12/2015
			{1207, "CNPJ do emitente inválido"},
			{1203, "Emitente não autorizado para uso do SAT"},
			{1229, "IE do emitente não informada C12 IE não corresponde ao Contribuinte de uso do SAT"},
			{1230, "IE do emitente diferente da IE do contribuinte autorizado para uso do SAT"}, // | Checar com dado recebido na parametrização do SAT
			{1457, "Código de Natureza da Operação para ISSQN inválido"},
			{1507, "Indicador de rateio para ISSQN inválido"},
			{1235, "CNPJ do destinatário inválido"},
			{1237, "CPF do destinatário inválido"},
			{1234, "Alerta Razão Social/Nome do destinatário em branco"}, //| Válido até 31/12/2015
			{1019, "Numeração dos itens não é sequencial crescente"},
			{1459, "Código do produto ou serviço em branco"},
			{1460, "GTIN do item (N) inválido | Validação do dígito verificador"},
			{1461, "Descrição do produto ou serviço em branco"},
			{1464, "Quantidade Comercial do item (N) inválido"},
			{1465, "Valor Unitário do item (N) inválido"},
			{1468, "Valor do Desconto do item (N) inválido"},
			{1469, "Valor de outras despesas acessórias do item (N) inválido"},
			{1535, "código da credenciadora de cartão de débito ou crédito inválido"},
			{1220, "Valor do rateio do desconto sobre subtotal do item (N) inválido"},
			{1228, "Valor do rateio do acréscimo sobre subtotal do item (N) inválido"},
			{1751, "não informado código do produto"}, //| Nova redação, efeitos a partir de 01.01.17.
			{1752, "código de produto informado fora do padrão ANP"}, //| Nova redação, efeitos a partir de 01.01.17.
			{1534, "Valor aproximado dos tributos do produto negativo"},
			{1533, "Valor aproximado dos tributos do CF-e_SAT negativo"},
			{1471, "Origem da mercadoria do Item (N) inválido (diferente de 0, 1, 2, 3, 4, 5, 6, 7, 8)"},
			{1472, "CST do Item (N) inválido (diferente de 00, 20, 90)"},
			{1473, "Alíquota efetiva do ICMS do item (N) não é maior ou igual a zero"},
			{1475, "CST do Item (N) inválido (diferente de 40 e 41 e 50 e 60)"},
			{1476, "Código de situação da operação - Simples Nacional - do Item (N) inválido (diferente de 102, 300 e 500)"},
			{1477, "Código de situação da operação - Simples Nacional - do Item (N) inválido (diferente de 900)"},
			{1478, "Código de Situação Tributária do PIS Inválido (diferente de 01, 02 e 05)"},
			{1479, "Base de cálculo do PIS do item (N) inválido"},
			{1480, "Alíquota do PIS do item (N) não é maior ou igual a zero"},
			{1482, "Código de Situação Tributária do PIS Inválido (diferente de 03)"},
			{1483, "Qtde Vendida do item (N) não é maior ou igual a zero"},
			{1484, "Alíquota do PIS em R$ do item (N) não é maior ou igual a zero"},
			{1486, "Código de Situação Tributária do PIS Inválido (diferente de 04, 06, 07, 08 e 09)"},
			{1487, "Código de Situação Tributária do PIS inválido (diferente de 49)"},
			{1488, "Código de Situação Tributária do PIS Inválido (diferente de 99)"},
			{1490, "Código de Situação Tributária da COFINS Inválido (diferente de 01, 02 e 05)"},
			{1491, "Base de cálculo do COFINS do item (N) inválido"},
			{1492, "Alíquota da COFINS do item (N) não é maior ou igual a zero"},
			{1494, "Código de Situação Tributária da COFINS Inválido (diferente de 03)"},
			{1496, "Alíquota da COFINS em R$ do item (N) não é maior ou igual a zero"},
			{1498, "Código de Situação Tributária da COFINS Inválido (diferente de 04, 06, 07, 08 e 09)"},
			{1499, "Código de Situação Tributária da COFINS Inválido (diferente de 49)"},
			{1500, "Código de Situação Tributária da COFINS Inválido (diferente de 99)"},
			{1501, "Operação com tributação de ISSQN sem informar a Inscrição Municipal"},
			{1503, "Valor das deduções para o ISSQN do item (N) não é maior ou igual a zero"},
			{1505, "Alíquota efetiva do ISSQN do item (N) não é maior ou igual a 2,00 (2%) e menor ou igual a 5,00 (5%)"},
			{1287, "Código Município do FG - ISSQN: dígito inválido. Exceto os códigos descritos no Anexo 2 que apresentam dígito inválido"},
			{1509, "Código municipal de Tributação do ISSQN do Item (N) em branco"},
			{1510, "Código de Natureza da Operação para ISSQN inválido"},
			{1511, "Indicador de Incentivo Fiscal do ISSQN do item (N) inválido (diferente de 1 e 2)"},
			{1527, "Código do Meio de Pagamento inválido"},
			{1528, "Valor do Meio de Pagamento inválido"},
			{1408, "Valor total do CF-e-SAT maior que o somatório dos valores de Meio de Pagamento empregados em seu pagamento"},
			{1409, "Valor total do CF-e-SAT supera o máximo permitido no arquivo de Parametrização de Uso"},
			{1073, "Valor de Desconto sobre total não é maior ou igual a zero"},
			{1074, "Valor de Acréscimo sobre total não é maior ou igual a zero"},
			{1084, "Erro Formatação do Certificado não é válido"},
			{1085, "Erro Assinatura do Aplicativo Comercial não confere com o registro do SAT"}, //| Válido até 31/12/2015
			{1998, "Não é possível gerar o cupom com os dados de entrada informados, pois resultam valores negativos"},
		};

		public static Dictionary<int, string> MotivoInvalidoCancelamento = new Dictionary<int, string>()
		{
			{1270, "Chave de acesso do CFe a ser cancelado inválido"},
			{1412, "CFe de cancelamento não corresponde a um CFe emitido nos 30 minutos anteriores ao pedido de cancelamento"},
			{1258, "Data/hora inválida. Problemas com o relógio interno do SAT-CF-e"},
			{1210, "Intervalo de tempo entre a emissão do CF-e a ser cancelado e a emissão do respectivo CF-e de cancelamento é maior que 30 (trinta) minutos"},
			{1454, "CNPJ da Software House inválido"},
			{1232, "CNPJ do destinatário do CF-e de cancelamento diferente daquele do CF-e a ser cancelado"},
			{1233, "CPF do destinatário do CF-e de cancelamento diferente daquele do CF-e a ser cancelado"},
			{1218, "Erro Chave de acesso do CF-e-SAT já consta como cancelado"}, //Nova redação a partir de 01.01.16
			{1999, "Erro não identificado"}, //Implementação facultativa até 31.12.15 e obrigatória a partir de 01.01.16.
		};
	}
}